//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string UserID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string AuditMessage { get; set; }
        public Nullable<bool> AdminOnly { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
