//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class Audit
    {
        public int ID { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }
        public string UserID { get; set; }
        public Nullable<int> EventID { get; set; }
        [AllowHtml]
        public string AuditMessage { get; set; }
        public Nullable<int> ReportID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
