//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSearch
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public short VolunteerQuantity { get; set; }
        public int Volunteers { get; set; }
        public byte Length { get; set; }
        public bool Published { get; set; }
        public bool Suspended { get; set; }
    }
}
