//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<short> OrganisationID { get; set; }
        public byte DayOfMonth { get; set; }
        public System.DateTime Expiry { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
    }
}
