//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class Profile
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public short Balance { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public bool Gender { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime BirthDate { get; set; }
        public string Phone { get; set; }
        [AllowHtml]
        public string Biography { get; set; }
        public string PictureURL { get; set; }
        public bool Active { get; set; }
        public bool Suspended { get; set; }
    
        public virtual User User { get; set; }
    }
}
