//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportStatistic
    {
        public Nullable<int> Month { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> Year { get; set; }
        public int ReportedCount { get; set; }
        public int ResolvedCount { get; set; }
        public int UresolvedCount { get; set; }
    }
}
