//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Transaction
    {
        public int ID { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }
        public string SenderID { get; set; }
        [Required]
        public string RecipientID { get; set; }
        public Nullable<int> EventID { get; set; }
        public bool Gift { get; set; }
        [Required]
        public short Amount { get; set; }
        public bool Cancelled { get; set; }
        [Required]
        public bool Complete { get; set; }
        public Nullable<int> ParentTransaction { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
