//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatistic
    {
        public Nullable<int> Month { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> Year { get; set; }
        public string UserID { get; set; }
        public Nullable<int> HostedCount { get; set; }
        public int VolunteerCount { get; set; }
        public int WithdrawnCount { get; set; }
        public int RejectedCount { get; set; }
        public int ConfirmedCount { get; set; }
        public int PendingConfirmationCount { get; set; }
    }
}
