//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class UserOrganisation
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public short OrganisationID { get; set; }
        public bool Approved { get; set; }
        public bool Denied { get; set; }
        public bool Admin { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Created { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
    }
}
