//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Volunteer
    {
        public int ID { get; set; }
        [Required]
        public int EventID { get; set; }
        [Required]
        public string VolunteerID { get; set; }
        [Required]
        public bool Accepted { get; set; }
        [Required]
        public bool Confirmed { get; set; }
        [Required]
        public bool Rejected { get; set; }
        [Required]
        public bool Withdrawn { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
